foodtrukus/config/routes.rb
Rails.application.routes.draw do
  get 'sign_in' => 'sessions#new'
  get 'sign_out' => 'sessions#destroy'

  resources :users
  resource :sessions, only: :create
  resources :food_trucks
  get 'splash' => 'pages#splash'
  root 'pages#splash'
  get 'map' => 'pages#map'

end

foodtrukus/app/models/food_truck.rb
class FoodTruck < ActiveRecord::Base
  belongs_to :user
end

foodtrukus/app/models/user.rb
class User < ActiveRecord::Base
  include Authem::User
  has_many :food_trucks
end

foodtrukus/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  authem_for :user

  decent_configuration do
    strategy DecentExposure::StrongParametersStrategy
  end

  def deny_user_access
      redirect_to :sign_in
  end
end

foodtrukus/app/controllers/food_trucks_controller.rb
class FoodTrucksController < ApplicationController
  expose(:food_trucks) {FoodTruck.where(user_id: current_user.id)}
  expose(:food_truck, attributes: :food_truck_params)

  def create
    if food_truck.save
      redirect_to food_trucks_path
    else
      respond_with food_truck
    end
  end

  alias update create

  def destroy
  end

  def show
  end
  
  def mapTrucks
    @geojson = Array.new

    FoodTruck.all.each do |food_truck|
      @geojson << {
       type: 'Feature',
        geometry: {
          type: 'Point',
          coordinates: [food_truck.longitude, food_truck.latitude]
        },
        properties: {
          name: food_truck.name,
          description: food_truck.description,
          :'marker-color' => '#00607d',
          :'marker-symbol' => 'circle',
          :'marker-size' => 'medium'
        }
      }
    end
  end
  
  respond_to do |format|
    format.html
    format.json { render json: @geojson }  # respond with the created JSON object
  end
  
  private

  def food_truck_params
    params.require(:food_truck).permit(:name, :description, :is_open, :open_until, :latitude, :longitude, :closing_time )
  end
end

foodtrukus/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def splash
  end
  def map
  end
end

foodtrukus/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  expose(:user) { User.find_by_email(params[:email]) }

  def create
    if user && user.authenticate(params[:password])
      sign_in(user)
      redirect_back_or_to(:food_trucks)
    elsif user
      render :new
    else
      new_user = User.create(email: params[:email], password: params[:password], password_confirmation: params[:password])
      if new_user.save
        sign_in(new_user)
        redirect_to food_trucks_path
      else
        render :new
      end
    end
  end

  def destroy
    sign_out_user
    redirect_to :root
  end
end

foodtrukus/app/controllers/users_controller.rb
class UsersController < ApplicationController
  expose(:users) {User.all}
  expose(:user, attributes: :user_params)
  before_filter :require_user

  def create
  end

  def update
  end

  def destroy
  end

  private

  def user_params
    params.require(:user).permit(:email)
  end
end

foodtrukus/app/helpers/application_helper.rb
module ApplicationHelper
end

foodtrukus/app/views/food_trucks/_food_truck_menu.html.haml
%body
  %ul.button-group
    %li
      %a.button{:href => map_path} Map
    %li
      %a.button{:href => food_trucks_path} List
    %li
      %a.button{:href => sign_out_path} Sign Out

foodtrukus/app/views/food_trucks/_form.html.haml
%dl
  %dt= f.label :name
  %dd= f.text_field :name
%dl
  %dt= f.label :description
  %dd= f.text_area :description
%dl
  %dt= f.label :closing_time
  %dd= f.time_field :closing_time
= f.submit "Save Truck", onclick: "this.form.submit(); this.disabled=true; this.value='Saving...';"
= link_to "Cancel", food_trucks_path

foodtrukus/app/views/food_trucks/_list.html.haml
%tr(data-id="#{food_truck.id}")
  %td= food_truck.name
  %td= food_truck.description
  %td= food_truck.closing_time.strftime("%I:%M %p") unless !food_truck.closing_time
  %td= food_truck.latitude
  %td= food_truck.longitude

foodtrukus/app/views/food_trucks/edit.html.haml
%h1 Edit Food Truck

=form_for food_truck, html: { multipart: true } do |f|
  =render "form", f: f

foodtrukus/app/views/food_trucks/index.html.haml
%div
  = render partial: "food_truck_menu"
  %h1 Trucks
  %table
    %thead
      %tr
        - ["Name", "Desc", "Open Until", "Lat", "Long"].each do |th|
          %th= th
    %tbody
      = render partial: 'food_trucks/list', collection: food_trucks, as: "food_truck"
  =button_to 'Add Truck', new_food_truck_path, method: :get

foodtrukus/app/views/food_trucks/new.html.haml
%h1 New Food Truck

=form_for food_truck, html: { multipart: true } do |f|
  =render "form", f: f

foodtrukus/app/views/layouts/application.html.haml
!!!
%html(lang="en-US")
  %head
    %title FoodTrukus
    %meta(charset="UTF-8")
    %meta(content="width=device-width, minimum-scale=1.0, maximum-scale=1.0" name="viewport")

    %script{:src => "https://api.mapbox.com/mapbox.js/v2.2.1/mapbox.js"}
    %link{:href => "https://api.mapbox.com/mapbox.js/v2.2.1/mapbox.css", :rel => "stylesheet"}/
    /[if lt IE 9]
      <link href='https://api.mapbox.com/mapbox.js/plugins/leaflet-locatecontrol/v0.43.0/L.Control.Locate.ie.css' rel='stylesheet' />
    %link{:href => "https://api.mapbox.com/mapbox.js/plugins/leaflet-locatecontrol/v0.43.0/css/font-awesome.min.css", :rel => "stylesheet"}/

    = stylesheet_link_tag "application"
    = stylesheet_link_tag "foundation_and_overrides"
    = javascript_include_tag "vendor/modernizr"
    /= javascript_include_tag "application"
    /[if IE]
      = javascript_include_tag "html5"

    = yield :head
    = csrf_meta_tags
    = yield

foodtrukus/app/views/pages/map.html.haml
%script{:src => "http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"}
%script{:src => "https://api.mapbox.com/mapbox.js/plugins/leaflet-locatecontrol/v0.43.0/L.Control.Locate.min.js"}
%link{:href => "https://api.mapbox.com/mapbox.js/plugins/leaflet-locatecontrol/v0.43.0/L.Control.Locate.mapbox.css", :rel => "stylesheet"}/
%div
  = render partial: "food_trucks/food_truck_menu"
  #map
  :javascript
  $(document).ready(function() {
    L.mapbox.accessToken = 'pk.eyJ1IjoianliMTMzNyIsImEiOiI4NjM2MzVmZGYwYTIzN2Q0YjI0OTI2OGNlNGViZjIxNSJ9.VL6UzFez-eOD10zx3eIYWA';
    var map = L.mapbox.map('map', 'mapbox.streets');
    var lc = L.control.locate({
      locateOptions: {
        maxZoom: 13
      }
    }).addTo(map);
    
    lc.start();
    
    map.on('dragstart', lc._stopFollowing, lc);
   
    var myLayer = L.mapbox.featureLayer().addTo(map);
   
    var geojson = 
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [ -79.932358, 32.874103]
      },
      "properties": {
        
        "name": "John\'s Waffles",
        "marker-color": "#00607d",
        "marker-size": "medium",
        "marker-symbol": "circle"
      }
    };
    myLayer.setGeoJSON(geojson) ;

foodtrukus/app/views/pages/splash.html.haml
.div
  %img{src: "/assets/foodtrukus-logo.jpg", alt: "FOODTRUK.US"}
.div
  %a.button{:href => food_trucks_path} Find Truks Near Me

foodtrukus/app/views/users/_list.html.haml
%tr(data-id="#{user.id}")
  %td= user.email
  %td

foodtrukus/app/views/users/edit.html.haml
%h1 My Account

=form_for user, html: { id: 'edit_user' } do |f|
  %dl
    %dt= f.label :email, 'Email'
    %dd= f.text_field :email
  = f.submit "Save user"
  = link_to "Go Back", users_path

foodtrukus/app/views/users/index.html.haml
%div
  %h1 user List
  %table
    %thead
      %tr
        - ["Email", ""].each do |th|
          %th= th
    %tbody
      = render partial: 'users/list', collection: users, as: "user"